"""Comprehensive pdf-studio showcase PDF — all features in one document.

Generates a 6-page PDF demonstrating every element across all three themes.
"""

from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from pdf_studio.document import Document
from pdf_studio.themes import Theme

OUT = Path("D:/Personal projects/pdf-studio/pdf-studio-showcase.pdf")


def build_comprehensive_showcase():
    """Build a single PDF cycling through all three themes per section."""
    doc = Document()  # no default theme — we'll set per section

    # ============================================================
    # PAGE 1: COVER + INTRODUCTION
    # ============================================================
    doc.add_heading("pdf-studio", level=0)
    doc.add_paragraph(
        "A thin, type-safe wrapper around ReportLab for developers who need "
        "real PDFs — tables, charts, headers, KPIs — without 300 lines of "
        "boilerplate. This document was generated by pdf-studio itself."
    )
    doc.add_heading("What's Inside", level=1)
    for item in [
        "Three research-backed themes (cypher / ledger / slate) — WCAG-AA verified",
        "Declarative templates: data → styled PDF in one call",
        "Real bold/italic via bundled Inter, Lora, JetBrains Mono TTFs",
        "Vector charts (matplotlib → SVG → PDF) — crisp at any zoom",
        "Styled tables with zebra striping, right-aligned numerics, captions",
        "KPI summary cards with green/red deltas",
        "Running headers with {page} / {total} placeholders",
        "Zero required dependencies beyond reportlab",
    ]:
        doc.add_bullet(item)

    doc.add_page_break()

    # ============================================================
    # PAGE 2: THEME PALETTE REFERENCE
    # ============================================================
    doc.add_heading("Theme Palettes", level=0)
    doc.add_paragraph(
        "Each theme is a complete visual language. Switching themes recolors "
        "headings, tables, charts, KPIs, bullets — no code changes."
    )

    themes = [
        ("cypher", "Navy foundation, teal accent. The brand default."),
        ("ledger", "Deep-green foundation, gold accent. Finance-optimised."),
        ("slate", "Indigo foundation, amber accent. Contemporary, warm."),
    ]

    for name, desc in themes:
        doc.theme = Theme.get(name)  # switch theme inline
        doc.add_heading(f"{name.title()} Theme", level=1)
        doc.add_paragraph(desc)
        t = doc.theme
        # Show colour swatches as a tiny table
        doc.add_table(
            [
                ["Role", "Hex", "Preview"],
                ["foundation", t.foundation, "■"],
                ["accent (fills)", t.accent, "■"],
                ["good (up)", t.good, "■"],
                ["bad (down)", t.bad, "■"],
                ["surface (cards)", t.surface, "■"],
                ["body text", t.body_text, "■"],
                ["muted text", t.muted_text, "■"],
                ["grid lines", t.grid, "■"],
            ],
            caption=f"{name} colour roles",
            right_align_cols=[],
        )
        doc.add_paragraph("")

    doc.add_page_break()

    # ============================================================
    # PAGE 3: TYPOGRAPHY + KPI + BULLETS
    # ============================================================
    doc.theme = Theme.get("cypher")
    doc.add_heading("Typography & Components", level=0)
    doc.add_heading("Heading Hierarchy", level=1)
    doc.add_heading("Level 1 — Section Heading", level=1)
    doc.add_heading("Level 2 — Subsection", level=2)
    doc.add_heading("Level 3 — Detail", level=3)

    doc.add_paragraph(
        "Body text uses the theme's <b>body_text</b> colour (Inter Regular). "
        "<b>Bold</b> and <i>italic</i> resolve to real bundled TTF weights — "
        "Inter-Bold, Lora-Italic, JetBrainsMono-Bold. No synthetic rendering."
    )

    doc.add_heading("KPI Summary Cards", level=1)
    doc.add_kpi_row([
        {"label": "AUM", "value": "₹1.24 L", "delta": "+4.1%"},
        {"label": "Realised P&L", "value": "₹8.3 K", "delta": "+12.4%"},
        {"label": "Max Drawdown", "value": "-6.2%", "delta": "-0.8%"},
        {"label": "Sharpe Ratio", "value": "1.84", "delta": "+0.12"},
    ])

    doc.add_heading("Feature Bullets", level=1)
    for item in [
        "Theme dataclass with 3 presets — one object, entire document recolored",
        "Document.from_template() — structured data → styled PDF in one call",
        "Charts render as vector SVG → PDF (crisp at any zoom level)",
        "Tables from pandas DataFrame or list-of-lists with right-aligned columns",
        "Thread-safe font registration with double-checked locking",
    ]:
        doc.add_bullet(item)

    doc.add_page_break()

    # ============================================================
    # PAGE 4: TABLES + BAR / LINE CHARTS
    # ============================================================
    doc.theme = Theme.get("ledger")
    doc.add_heading("Tables & Standard Charts", level=0)

    doc.add_heading("Holdings Table", level=1)
    doc.add_table(
        [
            ["Holding", "Sector", "Qty", "Avg Cost", "LTP", "Value", "P&L", "P&L %"],
            ["VEDL", "Metals", "50", "₹285", "₹312", "₹15,600", "₹1,350", "+9.5%"],
            ["ITC", "FMCG", "20", "₹412", "₹445", "₹8,900", "₹660", "+8.0%"],
            ["POWERGRID", "Utilities", "15", "₹198", "₹224", "₹3,360", "₹390", "+13.1%"],
            ["NMDC", "Metals", "50", "₹156", "₹172", "₹8,600", "₹800", "+10.3%"],
            ["CASTROLIND", "Energy", "30", "₹134", "₹142", "₹4,260", "₹240", "+6.0%"],
            ["SRF", "Chemicals", "4", "₹2,450", "₹2,620", "₹10,480", "₹680", "+6.9%"],
        ],
        caption="Table 1 — Portfolio positions (numeric columns right-aligned)",
        right_align_cols=[2, 3, 4, 5, 6, 7],
    )

    # Bar chart
    doc.add_heading("Bar Chart — Sector Allocation", level=1)
    fig, ax = plt.subplots(figsize=(6.3, 3.2), dpi=150)
    from pdf_studio.visuals import bar_chart
    fig_bar = bar_chart(
        ["Metals", "FMCG", "Utilities", "Energy", "Chemicals", "Cash"],
        [38, 22, 14, 18, 5, 3],
        title="Portfolio by Sector (%)",
        theme=doc.theme,
    )
    doc.add_chart(fig_bar, space_after=8)

    # Line chart
    doc.add_heading("Line Chart — Equity Curve vs Benchmark", level=1)
    from pdf_studio.visuals import line_chart
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"]
    fig_line = line_chart(
        months,
        {
            "Portfolio": [1.00, 1.03, 1.07, 1.05, 1.12, 1.15, 1.18, 1.24, 1.26, 1.28],
            "Nifty 50": [1.00, 1.02, 1.04, 1.03, 1.08, 1.10, 1.11, 1.13, 1.14, 1.15],
            "Nifty 200": [1.00, 1.01, 1.05, 1.04, 1.09, 1.12, 1.13, 1.16, 1.17, 1.18],
        },
        title="Normalised Returns (Jan = 1.00)",
        theme=doc.theme,
    )
    doc.add_chart(fig_line, space_after=8)

    doc.add_page_break()

    # ============================================================
    # PAGE 5: DONUT + HEATMAP + CHART ROW
    # ============================================================
    doc.theme = Theme.get("slate")
    doc.add_heading("Composition & Correlation", level=0)

    # Donut chart
    doc.add_heading("Donut Chart — Asset Composition", level=1)
    from pdf_studio.visuals import donut_chart
    fig_donut = donut_chart(
        ["Equity", "ETF", "Cash", "Bonds", "Alternatives"],
        [62, 20, 12, 4, 2],
        title="Allocation Breakdown",
        theme=doc.theme,
    )
    doc.add_chart(fig_donut, space_after=8)

    # Heatmap
    doc.add_heading("Heatmap — Sector Correlation Matrix", level=1)
    from pdf_studio.visuals import heatmap
    corr = [
        [1.00, 0.34, -0.12, 0.41, 0.05, 0.08],
        [0.34, 1.00, 0.08, 0.29, -0.02, 0.11],
        [-0.12, 0.08, 1.00, -0.15, 0.03, -0.04],
        [0.41, 0.29, -0.15, 1.00, 0.11, 0.07],
        [0.05, -0.02, 0.03, 0.11, 1.00, 0.02],
        [0.08, 0.11, -0.04, 0.07, 0.02, 1.00],
    ]
    labels = ["Metals", "FMCG", "Utilities", "Energy", "Chemicals", "Cash"]
    fig_heat = heatmap(
        corr, labels, title="Cross-Sector Correlation", diverging=True, theme=doc.theme
    )
    doc.add_chart(fig_heat, space_after=8)

    # Chart row (two charts side by side)
    doc.add_heading("Chart Row — Two Charts Side-by-Side", level=1)
    fig1 = bar_chart(["A", "B", "C"], [10, 20, 15], title="Left", theme=doc.theme)
    fig2 = donut_chart(["X", "Y"], [60, 40], title="Right", theme=doc.theme)
    doc.add_chart_row([fig1, fig2], space_after=8)

    doc.add_page_break()

    # ============================================================
    # PAGE 6: TEMPLATE DEMO + CLOSING
    # ============================================================
    doc.theme = Theme.get("cypher")
    doc.add_heading("Declarative Template", level=0)
    doc.add_paragraph(
        "The financial_statement template builds a complete report from structured "
        "data — no builder calls needed. One line of code."
    )

    # Show the template data as a table
    doc.add_heading("Input Data Structure", level=1)
    doc.add_table(
        [
            ["Key", "Type", "Example"],
            ["title", "str", "\"Q3 Portfolio Statement\""],
            ["subtitle", "str", "\"Generated via from_template()\""],
            ["kpis", "list[dict]", "[{\"label\": \"AUM\", \"value\": \"₹1.2L\", \"delta\": \"+4.1%\"}]"],
            ["composition", "tuple[list, list]", "([\"Equity\", \"Cash\"], [70, 30])"],
            ["table", "list[list]", "[[\"Holding\", \"Value\"], [\"VEDL\", \"₹15,600\"]]"],
            ["right_align_cols", "list[int]", "[1]"],
        ],
        caption="Template input schema",
        right_align_cols=[],
    )

    doc.add_heading("Usage", level=1)
    doc.add_paragraph(
        "```python\n"
        "from pdf_studio import Document\n\n"
        "data = {\n"
        '    "title": "Q3 Portfolio",\n'
        '    "kpis": [{"label": "AUM", "value": "₹1.2L", "delta": "+4.1%"}],\n'
        '    "composition": (["Equity", "Cash"], [70, 30]),\n'
        '    "table": [["Holding", "Value"], ["VEDL", "₹15,600"]],\n'
        '    "right_align_cols": [1],\n'
        "}\n"
        'doc = Document.from_template("financial_statement", data)\n'
        'doc.render("q3.pdf")\n'
        "```"
    )

    doc.add_heading("That's It", level=1)
    doc.add_paragraph(
        "Three themes. One template. Zero boilerplate. "
        "pip install pdf-studio and start generating."
    )
    doc.add_paragraph("")
    doc.add_paragraph("github.com/AshayK003/pdf-studio  |  AGPL v3")

    # Render
    doc.render(str(OUT))
    return OUT


if __name__ == "__main__":
    out = build_comprehensive_showcase()
    print(f"✅ Generated: {out} ({out.stat().st_size / 1024:.1f} KB)")

    # Also render first page as PNG for quick preview
    import fitz
    d = fitz.open(out)
    pix = d[0].get_pixmap(dpi=150)
    png = out.with_suffix(".png")
    pix.save(str(png))
    d.close()
    print(f"🖼️  Preview: {png}")